# shellcheck shell=bash
#
# Необязательный плановый перезапуск службы zapret.
#
# Это обходная мера, а не лечение: она маскирует причину того, что через
# несколько часов работы часть трафика перестаёт обходиться. Поэтому:
#   * по умолчанию выключено, включается только руками;
#   * каждый автоматический перезапуск пишет строку в лог, и менеджер
#     показывает их количество - чтобы "иногда подтупливает" превратилось
#     в число, с которым можно работать;
#   * интервал ограничен диапазоном 5-12 часов (по умолчанию 12): чаще -
#     это уже постоянные обрывы соединений, реже - бессмысленно;
#   * поддерживается только systemd. Для остальных init-систем таймеров нет,
#     а тащить в обходную меру cron с его различиями между дистрибутивами
#     не стоит - причину всё равно предстоит найти и убрать.
#
# Перезапуск рвёт активные соединения, поэтому момент срабатывания
# размазывается случайной задержкой: попасть ровно в разговор в Discord
# каждые 8 часов было бы обидно.

[ -n "${ZDY_AUTORESTART_SOURCED:-}" ] && return 0
ZDY_AUTORESTART_SOURCED=1

ZDY_SYSTEMD_UNIT_DIR="${ZDY_SYSTEMD_UNIT_DIR:-/etc/systemd/system}"
ZDY_HELPER_DIR="${ZDY_HELPER_DIR:-/usr/local/lib/zapret-discord-youtube}"
ZDY_AUTORESTART_LOG="${ZDY_AUTORESTART_LOG:-/var/log/zapret-autorestart.log}"

ZDY_AUTORESTART_NAME="zapret-autorestart"
ZDY_AUTORESTART_HELPER="$ZDY_HELPER_DIR/autorestart.sh"
ZDY_AUTORESTART_SERVICE="$ZDY_SYSTEMD_UNIT_DIR/$ZDY_AUTORESTART_NAME.service"
ZDY_AUTORESTART_TIMER="$ZDY_SYSTEMD_UNIT_DIR/$ZDY_AUTORESTART_NAME.timer"

ZDY_AUTORESTART_MIN_HOURS=5
ZDY_AUTORESTART_MAX_HOURS=12
ZDY_AUTORESTART_DEFAULT_HOURS=12

# Только systemd - сознательное ограничение, см. шапку файла.
autorestart_supported() {
  have_cmd systemctl && [ -d "$ZDY_SYSTEMD_UNIT_DIR" ]
}

autorestart_interval_valid() {
  local hours="$1"
  [[ "$hours" =~ ^[0-9]+$ ]] || return 1
  [ "$hours" -ge "$ZDY_AUTORESTART_MIN_HOURS" ] && [ "$hours" -le "$ZDY_AUTORESTART_MAX_HOURS" ]
}

# Команда перезапуска. Только systemd: автоперезапуск - временная заглушка,
# и тащить в неё матрицу из семи init-систем ради обходной меры не стоит.
autorestart_restart_command() {
  have_cmd systemctl || return 1
  printf 'systemctl restart %s\n' "$ZDY_SERVICE_NAME"
}

autorestart_write_helper() {
  local hours="$1" restart_cmd
  restart_cmd=$(autorestart_restart_command) || {
    err "Не удалось определить, как перезапускать службу на этой системе."
    return 1
  }

  mkdir_out "$ZDY_HELPER_DIR" || return 1

  # Намеренно /bin/sh: helper запускается системным планировщиком, и bash
  # там может не быть (Alpine, Chimera). По той же причине внутри нет ни
  # pgrep, ни ps -o - только чтение procfs.
  write_out "$ZDY_AUTORESTART_HELPER" <<EOF || return 1
#!/bin/sh
# Generated by zapret-manager. Scheduled zapret restart.
# To disable: zapret-manager -> Service -> Auto-restart.

log_file="$ZDY_AUTORESTART_LOG"

procs=0
for proc_dir in /proc/[0-9]*; do
    [ -r "\$proc_dir/comm" ] || continue
    read -r proc_name <"\$proc_dir/comm" 2>/dev/null || continue
    case "\$proc_name" in
        nfqws | tpws) procs=\$((procs + 1)) ;;
    esac
done

printf '%s restart interval=${hours}h nfqws_procs=%s\n' \\
    "\$(date '+%Y-%m-%d %H:%M:%S')" "\$procs" >>"\$log_file" 2>/dev/null

$restart_cmd
EOF

  chmod_out 755 "$ZDY_AUTORESTART_HELPER"
}

autorestart_enable_systemd() {
  local hours="$1"

  write_out "$ZDY_AUTORESTART_SERVICE" <<EOF || return 1
[Unit]
Description=Плановый перезапуск zapret (обходная мера)
Documentation=https://github.com/$ZDY_REPO_SLUG

[Service]
Type=oneshot
ExecStart=$ZDY_AUTORESTART_HELPER
EOF

  write_out "$ZDY_AUTORESTART_TIMER" <<EOF || return 1
[Unit]
Description=Плановый перезапуск zapret каждые ${hours} ч

[Timer]
OnBootSec=${hours}h
OnUnitActiveSec=${hours}h
# Чтобы перезапуск не приходился всегда на одну и ту же минуту.
RandomizedDelaySec=1800
AccuracySec=1min

[Install]
WantedBy=timers.target
EOF

  run_elevated systemctl daemon-reload || return 1
  run_elevated systemctl enable --now "$ZDY_AUTORESTART_NAME.timer"
}

autorestart_enable() {
  local hours="$1"

  autorestart_interval_valid "$hours" || {
    err "Интервал должен быть целым числом от $ZDY_AUTORESTART_MIN_HOURS до $ZDY_AUTORESTART_MAX_HOURS часов."
    return 1
  }

  require_elevation || return 1
  autorestart_write_helper "$hours" || return 1

  if ! autorestart_supported; then
    err "Автоперезапуск доступен только на системах с systemd."
    hint "На остальных init-системах пользуйтесь ручным перезапуском:"
    hint "  zapret-manager restart"
    return 1
  fi

  autorestart_enable_systemd "$hours" || return 1
  ok "Автоперезапуск включён: каждые ${hours} ч (systemd timer)"

  hint "Это обходная мера. Каждый перезапуск пишется в $ZDY_AUTORESTART_LOG."
  hint "Этот лог и снимки состояния понадобятся, когда будем искать причину."
}

autorestart_disable() {
  local removed=0

  require_elevation || return 1

  if [ -e "$ZDY_AUTORESTART_TIMER" ]; then
    run_elevated systemctl disable --now "$ZDY_AUTORESTART_NAME.timer" >/dev/null 2>&1 || true
    rm_out "$ZDY_AUTORESTART_TIMER"
    rm_out "$ZDY_AUTORESTART_SERVICE"
    run_elevated systemctl daemon-reload >/dev/null 2>&1 || true
    removed=1
  fi

  if [ "$removed" = "0" ]; then
    warn "Автоперезапуск и так выключен"
    return 0
  fi

  # Helper оставляем: он ничего не делает, пока его никто не вызывает,
  # а лог рядом с ним может ещё пригодиться при разборе.
  ok "Автоперезапуск выключен"
}

# Печатает off | systemd:<часы>
autorestart_status() {
  local line hours

  if [ -r "$ZDY_AUTORESTART_TIMER" ]; then
    while IFS= read -r line; do
      case "$line" in
        OnUnitActiveSec=*)
          hours="${line#OnUnitActiveSec=}"
          hours="${hours%h}"
          printf 'systemd:%s\n' "$hours"
          return 0
          ;;
      esac
    done <"$ZDY_AUTORESTART_TIMER"
    printf 'systemd:?\n'
    return 0
  fi

  printf 'off\n'
}

autorestart_status_text() {
  local status="${1:-$(autorestart_status)}"
  case "$status" in
    off) printf 'выключен\n' ;;
    systemd:*) printf 'каждые %s ч (systemd timer)\n' "${status#systemd:}" ;;
    *) printf 'неизвестно\n' ;;
  esac
}

# Сколько автоматических перезапусков было за последние N дней.
autorestart_log_count() {
  local days="${1:-7}" cutoff line count=0 stamp
  [ -r "$ZDY_AUTORESTART_LOG" ] || {
    printf '0\n'
    return
  }

  cutoff=$(date -d "-$days days" '+%Y-%m-%d' 2>/dev/null) || cutoff=""
  if [ -z "$cutoff" ]; then
    grep -c . "$ZDY_AUTORESTART_LOG" 2>/dev/null || printf '0\n'
    return
  fi

  while IFS= read -r line; do
    stamp="${line%% *}"
    [[ "$stamp" > "$cutoff" || "$stamp" == "$cutoff" ]] && count=$((count + 1))
  done <"$ZDY_AUTORESTART_LOG"

  printf '%s\n' "$count"
}
